[package]
name = "dstsmodel"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
half = "2.6"
quick-xml = "0.38"
nalgebra-glm = { version = "0.20", features = ["serde-serialize"] }
nalgebra = "*"
